version: "3.7"

services:
  typst:
    image: ghcr.io/typst/typst:v0.10.0
    entrypoint: typst
    command: watch presentation.typ
    environment:
      TYPST_FONT_PATHS: ./fonts
    volumes:
      - .:/root:Z
